#!/bin/bash
# By: David
# Date: September 30th, 2018
#
# Usage: Bind this file as executable + the command line paramaters:
#				 next, prev, volumeUp, volumeDown to media keys. And set the 
#	       variable mpd_ip to your mpd servers local ip 
#
# Requires: python3 and Garrett Holbrook's volume-change.py

mpd_ip=192.168.1.10
mpdhost=`mpc -h $mpd_ip`
display_notifications=false

next ()
{
	if [[ $mpdhost == *"[playing]"* ]]; then
		mpc -h $mpd_ip next
		if [ "$display_notifications" = true ]; then
			notify-send --hint=int:transient:1 -t 1000 "MPD" "`mpc -h $mpd_ip current`"
		fi
	#else
		#do something when not using media keys for mpd
	fi
}

prev ()
{
	if [[ $mpdhost == *"[playing]"* ]]; then
		mpc -h $mpd_ip prev
		if [ "$display_notifications" = true ]; then
			notify-send --hint=int:transient:1 -t 1000 "MPD" "`mpc -h $mpd_ip current`"
		fi
	#else
		#do something when not using media keys for mpd  
	fi
}

toggle ()
{
	mpc -h $mpd_ip toggle
	if [ "$display_notifications" = true ]; then
  	notify-send --hint=int:transient:1 -t 1000 "MPD" "`mpc -h $mpd_ip | sed -n 2p`" && notify-send --hint=int:transient:1 -t 1000 "MPD" "`mpc -h $mpd_ip current`"
	fi
}

volumeUp ()
{
	if [[ $mpdhost == *"[playing]"* ]]; then
		mpc -h $mpd_ip volume +1
	else
		#amixer -D pulse sset Master 3%+
		volume-change.py increase 3
	fi
}

volumeDown ()
{
	if [[ $mpdhost == *"[playing]"* ]]; then
		mpc -h $mpd_ip volume -1
	else
		#amixer -D pulse sset Master 3%+
		volume-change.py decrease 3
	fi
}

case "$1" in
     next)
        next
            ;;
     prev)
        prev
        
            ;;
     toggle)
				toggle
            ;;
#     stop)
#        mpc -h 192.168.1.10 stop 
#        notify-send --hint=int:transient:1 -t 1000 "MPD" "stopped"
#            ;;
     volumeUp)
        volumeUp
            ;;
     volumeDown)
        volumeDown
            ;;
esac

exit 0
